---

# Disable IPv6

- name: disable_all_ipv6
  sysctl:
    name:       "net.ipv6.conf.all.disable_ipv6"
    value:      1
    sysctl_set: yes

- name: disable_default_ipv6
  sysctl:
    name:       "net.ipv6.conf.default.disable_ipv6"
    value:      1
    sysctl_set: yes

- name: disable_lo_ipv6
  sysctl:
    name:       "net.ipv6.conf.lo.disable_ipv6"
    value:      1
    sysctl_set: yes
    reload:     yes

# APT repos

- name: add_mesosphere_apt_key
  when: ipv6_lo_disabled|success
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id:        E56151BF
  register: add_mesosphere_apt_key

# APT keys

- name: add_mesosphere_apt_repo
  when: mesosphere_apt_key_added|success
  apt_repository:
    repo:         "deb http://repos.mesosphere.io/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} main"
    state:        present
    update_cache: yes
  register: add_mesosphere_apt_repo

# Packages

- name: install_python_httplib2
  apt:
    name: python-httplib2
    update_cache: yes
