---

# Name:          main.yaml
# Author:        Daniel Middleton <me@daniel-middleton.com>
# Description:   Ansible Playbook for mesos hosts.

###############################################################################
############################# Network configuration ###########################

### Disable IPv6

- name: Disable all IPv6
  sysctl: >
          name="net.ipv6.conf.all.disable_ipv6"
          value=1
          sysctl_set=yes
  register: ipv6_all_disabled

- name: Disable default IPv6
  when: ipv6_all_disabled|success
  sysctl: >
          name="net.ipv6.conf.default.disable_ipv6"
          value=1
          sysctl_set=yes
  register: ipv6_default_disabled

- name: Disable lo IPv6
  when: ipv6_default_disabled|success
  sysctl: >
          name="net.ipv6.conf.lo.disable_ipv6"
          value=1
          sysctl_set=yes
          reload=yes
  register: ipv6_lo_disabled

###############################################################################
############################## Repo installation ##############################

### Mesosphere

# Add Mesosphere APT repo
- name: Add Mesosphere APT key
  when: ipv6_lo_disabled|success
  apt_key: >
           keyserver=hkp://keyserver.ubuntu.com:80
           id=E56151BF
  register: mesosphere_apt_key_added

# Add Mesosphere APT key
- name: Add Mesosphere APT repo
  when: mesosphere_apt_key_added|success
  apt_repository: >
                  repo="deb http://repos.mesosphere.io/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} main"
                  state=present
                  update_cache=yes
  register: mesosphere_apt_repo_added

###############################################################################
############################# Package installation ############################

### NTP

# Install the NTP package
- name: Install NTP
  when: mesosphere_apt_repo_added|success
  apt: >
       name=ntp
       update_cache=yes
  register: ntp_installed

### python-httplib2

# Install the python-httplib2 package, used by Ansible's uri module
- name: Install python-httplib2
  when: ntp_installed|success
  apt: >
       name=python-httplib2
       update_cache=yes
  register: httplib2_installed
